// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1ZRNU-XDA7kTYfAtCM0-aVuzf-5p8Gpw',
    appId: '1:1010176194732:web:2c5b2f938b55e681634709',
    messagingSenderId: '1010176194732',
    projectId: 'wine-and-movie',
    authDomain: 'wine-and-movie.firebaseapp.com',
    storageBucket: 'wine-and-movie.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6dJowkp6_SeW0RoOEkRd4xrEV-yxlBz0',
    appId: '1:1010176194732:ios:f0bf952528b82d2e634709',
    messagingSenderId: '1010176194732',
    projectId: 'wine-and-movie',
    storageBucket: 'wine-and-movie.firebasestorage.app',
    iosBundleId: 'app.wam.wineandmovie',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZOPl7pQpFShCIOZrAGQh5wHvrs7b4M7Y',
    appId: '1:1010176194732:android:91afc267098340ef634709',
    messagingSenderId: '1010176194732',
    projectId: 'wine-and-movie',
    storageBucket: 'wine-and-movie.firebasestorage.app',
  );

}